package residencia.modelo.entidad;
// Generated 21/05/2015 03:02:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CobroExtra generated by hbm2java
 */
public class CobroExtra  implements java.io.Serializable {


     private String idCobroExtra;
     private String idContrato;
     private String idHabitacion;
     private BigDecimal monto;

    public CobroExtra() {
    }

	
    public CobroExtra(String idCobroExtra) {
        this.idCobroExtra = idCobroExtra;
    }
    public CobroExtra(String idCobroExtra, String idContrato, String idHabitacion, BigDecimal monto) {
       this.idCobroExtra = idCobroExtra;
       this.idContrato = idContrato;
       this.idHabitacion = idHabitacion;
       this.monto = monto;
    }
   
    public String getIdCobroExtra() {
        return this.idCobroExtra;
    }
    
    public void setIdCobroExtra(String idCobroExtra) {
        this.idCobroExtra = idCobroExtra;
    }
    public String getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(String idContrato) {
        this.idContrato = idContrato;
    }
    public String getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(String idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


