package residencia.modelo.entidad;
// Generated 21/05/2015 03:02:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private String idHabitacion;
     private BigDecimal numeroCuarto;
     private BigDecimal numeroPiso;
     private BigDecimal totalInquilinoCuarto;
     private BigDecimal precioHabitacion;

    public Habitacion() {
    }

	
    public Habitacion(String idHabitacion, BigDecimal numeroCuarto, BigDecimal numeroPiso, BigDecimal precioHabitacion) {
        this.idHabitacion = idHabitacion;
        this.numeroCuarto = numeroCuarto;
        this.numeroPiso = numeroPiso;
        this.precioHabitacion = precioHabitacion;
    }
    public Habitacion(String idHabitacion, BigDecimal numeroCuarto, BigDecimal numeroPiso, BigDecimal totalInquilinoCuarto, BigDecimal precioHabitacion) {
       this.idHabitacion = idHabitacion;
       this.numeroCuarto = numeroCuarto;
       this.numeroPiso = numeroPiso;
       this.totalInquilinoCuarto = totalInquilinoCuarto;
       this.precioHabitacion = precioHabitacion;
    }
   
    public String getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(String idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public BigDecimal getNumeroCuarto() {
        return this.numeroCuarto;
    }
    
    public void setNumeroCuarto(BigDecimal numeroCuarto) {
        this.numeroCuarto = numeroCuarto;
    }
    public BigDecimal getNumeroPiso() {
        return this.numeroPiso;
    }
    
    public void setNumeroPiso(BigDecimal numeroPiso) {
        this.numeroPiso = numeroPiso;
    }
    public BigDecimal getTotalInquilinoCuarto() {
        return this.totalInquilinoCuarto;
    }
    
    public void setTotalInquilinoCuarto(BigDecimal totalInquilinoCuarto) {
        this.totalInquilinoCuarto = totalInquilinoCuarto;
    }
    public BigDecimal getPrecioHabitacion() {
        return this.precioHabitacion;
    }
    
    public void setPrecioHabitacion(BigDecimal precioHabitacion) {
        this.precioHabitacion = precioHabitacion;
    }




}


