package residencia.modelo.entidad;
// Generated 21/05/2015 03:02:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Observacion generated by hbm2java
 */
public class Observacion  implements java.io.Serializable {


     private String idObservacion;
     private String idUsuario;
     private String idPersona;
     private Date fecha;
     private String concepto;

    public Observacion() {
    }

	
    public Observacion(String idObservacion) {
        this.idObservacion = idObservacion;
    }
    public Observacion(String idObservacion, String idUsuario, String idPersona, Date fecha, String concepto) {
       this.idObservacion = idObservacion;
       this.idUsuario = idUsuario;
       this.idPersona = idPersona;
       this.fecha = fecha;
       this.concepto = concepto;
    }
   
    public String getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(String idObservacion) {
        this.idObservacion = idObservacion;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }




}


