package residencia.modelo.entidad;
// Generated 05/06/2015 07:56:20 AM by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private String idOcupacion;
     private String nombre;

    public Ocupacion() {
    }

	
    public Ocupacion(String idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public Ocupacion(String idOcupacion, String nombre) {
       this.idOcupacion = idOcupacion;
       this.nombre = nombre;
    }
   
    public String getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(String idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


